### ISSUE TITLE
Change Dynamic Nav

### ISSUE THREAD

**Issue by arb** [continuationlabs/hapchat#28]
So the nav thing won't work as it currently stands. If you start logged out, hit the page, log in, and the go back to "/", you will still see login, instead of upload because you've got cached version of the home page.

Two options:
1. Expire the cache of the home page
2. Draw the nav client side

I personally prefer 1 because it would probably be easier and I like to handle security things like the server side.

**Comment by jaw187** [comment]
It's not a cache issue, once #25 is merged, the only way to access session data is to configure auth for the page.  Since the homepage doesn't have auth configured, the user is not authenticated.  As I tested auth I got hung up on this for a while.  But in the end, clicking login from the homepage every time doesn't add any clicks to a user who is already logged in.

One thought I had was to change "Login" to "Get started"....

**Comment by arb** [comment]
It was merged and it's still an issue. I login, upload a photo, go back to home, and I don't see the "photos" option anymore.
